website/views.py
'''
Main views of shop-easy app
'''

import logging
from flask import Blueprint, render_template, request, flash, redirect, url_for, jsonify
from flask_login import login_required, current_user

from student.inventory_details import get_inventory_details, \
    get_inventory_product
from student.cart import add_cart, clear_cart
from admin.inventory import add, update, delete
from admin.order import get_all_orders
from student.cart import get_cart_details, get_user_inventory_details
from student.order import get_order_details, get_ordered_products, place_order, cancel_order
from website import mail
from flask_mail import Message

views = Blueprint('views', __name__)

@views.route('/')
def home():
    return render_template("home.html")

@views.route('/get-inventory', methods=['GET'])
@login_required
def get_inventory():
    try:
        inventory_products = get_inventory_details()
        if inventory_products:
            unique_categories = set(product.category for product in inventory_products)
            return render_template("get_inventory.html", products=inventory_products,
                                   categories=unique_categories)
        else:
            return render_template("get_inventory.html", products=[],
                                   categories=[])
    except Exception as e:
        logging.exception(e)

@views.route('add-inventory', methods=['GET','POST'])
@login_required
def add_inventory():
    if request.method == 'POST': 
        name = request.form.get("name")
        description = request.form.get("description")
        quantity = int(request.form.get("quantity"))
        category = request.form.get("category")
        weight = int(request.form.get("weight"))
        print(request.form.get("expiry_date"))
        expiry_date =request.form.get("expiry_date")
        print(f"Name: {name}, Description: {description}, Quantity: {quantity}, Category: {category}, Weight: {weight}, Expiry Date: {expiry_date}")
        # Validating the null check of input fields
        if any(value is None or value == "" for value in (name, description, quantity, category, weight, expiry_date)):
            flash("One or more form values are missing", category='error')
            return render_template("login.html", user=current_user)   
        else:
            status = add(name, description, quantity, category, weight, expiry_date)
            return render_template("admin.html", user=current_user) if status else render_template("add_products.html", user=current_user)
    else:
        return render_template("add_products.html", user=current_user)
    

@views.route('student/add-to-cart', methods=['POST'])
@login_required
def add_to_cart():
    try:
        data = request.get_json()
        product_id = data.get('productId')
        quantity = data.get('quantity')
        add_cart(product_id,quantity)  
        return jsonify({'message': 'Item added to cart successfully'}), 200
    except Exception as e:
        logging.exception(e)
        return jsonify({'message': 'Sorry! Unexpected error occured while adding the item to the cart'}), 500

@views.route('/cart', methods=['GET'])
@login_required
def get_cart():
    try:
        cart_details = get_cart_details(current_user)
        inventory_details = get_user_inventory_details(current_user)
        mapping_dict = {product.sku: product for product in cart_details}
        cart_products = [
            {"sku": product_details.sku,
            "name": product_details.name,
            "quantity": mapping_dict[product_details.sku].quantity}
            for product_details in inventory_details
            if product_details.sku in mapping_dict
        ]
        total_quantity = sum(product['quantity'] for product in cart_products)
        if cart_products:
            return render_template("checkout.html", cart_details=cart_products,
                                   total_quantity=total_quantity)
        flash("Cart is Empty !!", category='error')
        return render_template("checkout.html", cart_details=[],
                                   total_quantity=0)
    except Exception as e:
        logging.exception(e)
        return render_template("checkout.html", cart_details=[],
                                   total_quantity=0)


@views.route('/products', methods=['GET'])
@login_required
def get_products():
    try:
        inventory_products = get_inventory_details()
        if inventory_products:
            return render_template("products.html", products=inventory_products)
        else:
            return render_template("products.html", products=[])
    except Exception as e:
        logging.exception(e)

@views.route('/edit_product/<sku>', methods=['GET', 'POST'])
def edit_product(sku):
    
    product = get_inventory_product(sku)

    if request.method == 'POST':
        name = request.form.get("name")
        description = request.form.get("description")
        quantity = request.form.get("quantity")
        category = request.form.get("category")
        weight = request.form.get("weight")
        expiry_date = request.form.get("expiry_date")
        
        if any(value is None or value == "" for value in (name, description, quantity, category, weight, expiry_date)):
            flash("One or more form values are missing", category='error')
        else:
            status = update(product, name, description, quantity, category, weight, expiry_date)
            if status:
                flash("Product updated successfully !", category='success')
                return render_template('admin.html')
            else:
                flash("Product update failed !", category='error')
       
    return render_template('update_product.html', product=product)


@views.route('/delete_product/<sku>', methods=['DELETE'])
def delete_product(sku):

    product = get_inventory_product(sku)

    if product:
        status = delete(product)
        if status:
            flash("Product deleted successfully!", category='success')
            response_data = {'status': 'success', 'message': 'Product deleted successfully!'}
        else:
            flash("Product deletion failed!", category='error')
            response_data = {'status': 'error', 'message': 'Product deletion found'}
    else:
        flash("Product not found", category='error')
        response_data = {'status': 'error', 'message': 'Product not found'}
    
    return jsonify(response_data)

@views.route('/orders', methods=['GET'])
@login_required
def get_orders():
    try:
        order_details = get_order_details(current_user)
        products_ordered = get_ordered_products(order_details)
        if not products_ordered:
            flash("No order history available !!", category='success')
        return render_template('order.html', orders=products_ordered)
    except Exception as e:
        logging.exception(e)
        return render_template('order.html', orders=[])
    
@views.route('student/place-order', methods=['POST'])
@login_required
def order():
    try:
        data = request.get_json()
        cart_details = data['cartDetails']
        user_email = current_user.email
        user_cart = current_user.carts
        clear_cart(user_cart[0])
        place_order(cart_details)
        send_order_notification(user_email)
        flash('Order placed successfully')
        return jsonify({'message': 'Order placed successfully'}), 201
    except Exception as e:
        logging.exception(e)
        flash('Sorry! Order placement Failed')
        return jsonify({'message': 'Sorry! Unexpected error occured while placing the order'}), 500
    
def send_order_notification(recipient_email):
    try:
        subject = 'Order Confirmation'
        body = f'Thank you for your order!\n\n Your order has been placed successfully !!'
        message = Message(subject=subject, recipients=[recipient_email], body=body)
        mail.send(message)
    except Exception as e:
        logging.exception(e)


@views.route('student/cancel', methods=['PUT'])
@login_required
def cancel():
    try:
        order_id = request.get_json().get('order_id')
        status = cancel_order(order_id)  
        if status:
            return jsonify({'message': 'Order cancelled successfully'}), 200
        else:
            return jsonify({'message': 'Sorry! Unable to cancel the order'}), 500
    except Exception as e:
        logging.exception(e)
        return jsonify({'message': 'Sorry! Unexpected error occured while cancelling the order'}), 500
    

@views.route('all-orders', methods=['GET'])
@login_required 
def get_all_orders_list():
    try:
        all_orders = get_all_orders()
        if not all_orders:
            flash("No order history available !!", category='success')
        return render_template('all_orders.html', orders=all_orders)
    except Exception as e:
        logging.exception(e)
        return render_template('all_orders.html', orders=[])

website/templates/add_products.html
{% extends "base.html" %} {% block title %} Add Product {% endblock %} {% block
navbar %} {# Empty block to exclude the navigation bar in products.html #} {%
endblock %} {% block content %} {# Empty block to exclude the content #} {%
endblock %} {% block admin%}

<div class="container-md">
  <h2 class="mt-4 mb-4">Add Product To Inventory</h2>
  <form
    id="addprod"
    action="{{ url_for('views.add_inventory') }}"
    method="post"
    class="mx-auto"
  >
    <div class="form-group row mb-3">
      <label for="name" class="col-md-6 col-form-label"
        ><strong>Product Name</strong></label
      >
      <div class="col-md-6">
        <input
          type="text"
          id="name"
          name="name"
          class="form-control"
          required
        />
      </div>
    </div>

    <div class="form-group row mb-3">
      <label for="description" class="col-md-6 col-form-label"
        ><strong>Description</strong></label
      >
      <div class="col-md-6">
        <textarea
          type="text"
          id="description"
          name="description"
          class="form-control"
          required
        ></textarea>
      </div>
    </div>

    <div class="form-group row mb-3">
      <label for="quantity" class="col-md-6 col-form-label"
        ><strong>Quantity</strong></label
      >
      <div class="col-md-6">
        <input
          type="number"
          id="quantity"
          name="quantity"
          class="form-control"
          required
        />
      </div>
    </div>

    <div class="form-group row mb-3">
      <label for="category" class="col-md-6 col-form-label"
        ><strong>Category</strong></label
      >
      <div class="col-md-6">
        <input
          type="text"
          id="category"
          name="category"
          class="form-control"
          required
        />
      </div>
    </div>

    <div class="form-group row mb-3">
      <label for="weight" class="col-md-6 col-form-label"
        ><strong>Weight</strong></label
      >
      <div class="col-md-6">
        <input
          type="number"
          id="weight"
          name="weight"
          class="form-control"
          required
        />
      </div>
    </div>

    <div class="form-group row mb-3">
      <label for="expiry_date" class="col-md-6 col-form-label"
        ><strong>Expiry Date</strong></label
      >
      <div class="col-md-6">
        <input
          type="date"
          id="expiry_date"
          name="expiry_date"
          class="form-control"
          required
        />
      </div>
    </div>

    <div class="form-group row mt-5">
      <div class="col-md-6 offset-md-5">
        <button type="submit" class="btn btn-primary">Add Product</button>
      </div>
    </div>
  </form>
</div>
<script src="{{ url_for('static', filename='script.js') }}"></script>
{% endblock %}

website/templates/admin.html
{% extends "base.html" %} {% block title %}Admin{% endblock %} {% block content
%}
<div class="container vh-100">
  <div class="row">
    <div class="col-md-3 mt-4">
      <div class="card">
        <div class="card-header inventory-font">
          <strong>Admin operations</strong>
        </div>
        <div class="card-body">
          <div class="list-group" id="adminList">
            <a
              href="#"
              data-target="dashboard"
              class="list-group-item list-group-item-action inventory-font"
              >Dashboard</a
            >
            <a
              href="#"
              data-target="add-products"
              class="list-group-item list-group-item-action inventory-font"
              >Add Products</a
            >
            <a
              href="#"
              data-target="products"
              class="list-group-item list-group-item-action inventory-font"
              >Products</a
            >
            <a
              href="#"
              data-target="orders-list"
              class="list-group-item list-group-item-action inventory-font"
              >Orders</a
            >
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-9" id="content-container"></div>
  </div>
</div>

{% endblock %}

website/templates/all_orders.html
{% extends "base.html" %} {% block title %} Orders List {% endblock %} {% block
navbar %} {# Empty block to exclude the navigation bar in products.html #} {%
endblock %} {% block content %} {# Empty block to exclude the content #} {%
endblock %} {% block admin%}

<div class="container">
  <h2 class="mt-4 mb-4">Orders List</h2>

  <div class="table-responsive">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Order ID</th>
          <th>User Name</th>
          <th>User Email</th>
          <th>Units sold</th>
          <th>Date</th>
          <th>Status</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for order in orders %}
        <tr>
          <td>{{ order.order_id }}</td>
          <td>{{ order.name }}</td>
          <td>{{ order.email }}</td>
          <td>{{ order.units_sold }}</td>
          <td>{{ order.date }}</td>
          <td>{{ order.order_status }}</td>
          <td>
            <a
              href="#"
              class="btn btn-primary btn-sm edit-product"
              data-sku="{{ order.order_id }}"
            >
              Edit
            </a>
            <a
              href="#"
              class="btn btn-danger btn-sm delete-product"
              data-sku="{{ order.order_id }}"
            >
              Delete
            </a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<script
  type="text/javascript"
  src="{{ url_for('static', filename='js/admin.js') }}"
></script>

{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='css/styles.css') }}"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
      integrity="sha384-twcuYPV86B3vvpwNhWJuaLdUSLF9+ttgM2A6M870UYXrOsxKfER2MKox5cirApyA"
      crossorigin="anonymous"
    />
    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body class="background-gradient">
    {% block navbar %}
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="/">Portland State University Shop Easy</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbar"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbar">
          <ul class="navbar-nav ms-auto">
            {% if current_user.is_authenticated %} {% if current_user.role ==
            'student' %}
            <li class="nav-item">
              <a class="nav-link" id="cart" href="/cart">
                <i class="fas fa-shopping-cart"></i> Cart
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" id="orders" href="/orders">Orders</a>
            </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link" id="logout" href="/logout">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" id="login" href="/login">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" id="login" href="/">Information</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" id="login" href="/">Resources</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    {% endblock %} {% with messages = get_flashed_messages(with_categories=true)
    %} {% if messages %} {% for category, message in messages %} {% if category
    == 'error' %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      {{ message }}
      <button
        type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close"
      ></button>
    </div>
    {% else %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      {{ message }}
      <button
        type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close"
      ></button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div>
      <div class="container">{% block content %} {% endblock %}</div>
    </div>
    <div>{% block admin%} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.6.0.min.js"
      integrity="sha384-vtXRMe3mGCbOeY7l30aIg8H9p3GdeSe4IFlP6G8JMa7o7lXvnz3GFKzPxzJdPfGK"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
      integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/js/all.min.js"
      integrity="sha384-sCgwm7cN2+PN5J6MEF+tnqkCY4Wc5WRcGU+I9b04LSQaPRMO09dnbrVilAWAbH1z"
      crossorigin="anonymous"
    ></script>
    <script
      type="text/javascript"
      src="{{ url_for('static', filename='js/index.js') }}"
    ></script>
    <script
      type="text/javascript"
      src="{{ url_for('static', filename='js/add_to_cart.js') }}"
    ></script>
    <script
      type="text/javascript"
      src="{{ url_for('static', filename='js/admin.js') }}"
    ></script>
    <script
      type="text/javascript"
      src="{{ url_for('static', filename='js/checkout.js') }}"
    ></script>
  </body>
</html>

website/templates/checkout.html
{% extends "base.html" %} {% block title %}Checkout Page{% endblock %} {% block
content %}
<div class="container d-flex justify-content-center align-items-center vh-100">
  <div class="col-md-6 text-center">
    <h3 align="center">Checkout</h3>
    <div class="table-responsive">
      <table class="table" style="margin: 0 auto; width: 70%">
        <thead>
          <tr style="text-align: center">
            <th>Product</th>
            <th>Quantity</th>
          </tr>
        </thead>
        <tbody id="cartItemsTable">
          {% for product in cart_details %}
          <tr style="text-align: center">
            <td>{{ product.name }}</td>
            <td>{{ product.quantity }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <div
      id="totalQuantity"
      style="
        display: flex;
        justify-content: center;
        align-items: center;
        margin-top: 10px;
      "
    >
      <strong>Total Quantity: {{ total_quantity }}</strong>
    </div>
    <div style="margin-bottom: 20px"></div>
    <div align="center">
      <button
        id="checkoutBtn"
        class="btn btn-primary"
        data-cart-details="{{ cart_details }}"
      >
        Checkout
      </button>
    </div>
  </div>
</div>
{% endblock %}

website/templates/get_inventory.html
{% extends "base.html" %} {% block title %}Inventory Products{% endblock %} {%
block content %}
<div class="container vh-100">
  <div class="row">
    <div class="col-12" id="alert-container"></div>
  </div>
  <div class="row">
    <div class="col-md-3 mt-4">
      <div class="card">
        <div class="card-header inventory-font">
          <strong>Categories</strong>
        </div>
        <div class="card-body">
          <div class="list-group" id="categoryList">
            <a
              href="#"
              class="list-group-item list-group-item-action inventory-font"
              data-category="all"
              >All Categories</a
            >
            {% for category in categories %}
            <a
              href="#"
              class="list-group-item list-group-item-action inventory-font"
              data-category="{{ category }}"
            >
              {{ category }}
            </a>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-9 mt-4">
      <div class="row" id="product-container">
        {% for product in products %}
        <div class="col-md-4" data-category="{{ product.category }}">
          <div class="card mb-3">
            <img src="" class="card-img-top" alt="" />
            <div class="card-body">
              <h5 class="card-title inventory-font">{{ product.name }}</h5>
              <p class="card-text custom-card-text">
                Available Qty: {{ product.quantity }}
              </p>
              <p class="card-text custom-card-text">
                Expiry date: {{ product.format_date() }}
              </p>
              <div class="input-group mb-3">
                <div class="input-group-prepend">
                  <label
                    class="input-group-text custom-card-text"
                    for="quantity"
                    >Quantity</label
                  >
                </div>
                <select
                  class="custom-select"
                  id="quantity_{{ product.sku }}"
                  name="quantity"
                >
                  <option>1</option>
                  <option>2</option>
                  <option>3</option>
                  <option>4</option>
                </select>
              </div>

              <button
                class="btn btn-primary addToCartButton col-12"
                data-sku="{{ product.sku }}"
              >
                Add to Cart
              </button>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock %}

website/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content
%}
<div class="container">
  <div class="row">
    <div class="col-md-6 mt-4">
      <img
        src="../static/img/psu-shop-easy.png"
        alt="A Beautiful Landscape"
        class="img-fluid"
      />
    </div>
    <div
      class="col-md-6 d-flex align-items-center justify-content-center"
      style="min-height: 100vh"
    >
      <div>
        <div class="text-center mb-4">
          <h5 class="custom-font">Free groceries for all PSU Students !!</h5>
        </div>
        <div class="text-center mb-4">
          <a href="/login">
            <button type="button" class="btn btn-dark all-btn-size">
              Login
            </button></a
          >
        </div>
        <div class="text-center mb-4">
          <button type="button" class="btn btn-dark all-btn-size">
            Volunteer
          </button>
        </div>
        <div class="text-center mb-4">
          <button type="button" class="btn btn-dark all-btn-size">
            Donate
          </button>
        </div>
      </div>
    </div>

    {% endblock %}
  </div>
</div>

website/templates/index.html
{% extends "base.html" %} {% block title %}Add Product{% endblock %} {% block
content %}
<div class="container-md vh-100">
  <h2 class="mt-4 mb-4">Add Product To Inventory</h2>
  <form
    id="addprod"
    action="{{ url_for('views.add_inventory') }}"
    method="post"
    class="mx-auto"
  >
    <div class="form-group row mb-3">
      <label for="name" class="col-md-6 col-form-label"
        ><strong>Product Name:</strong></label
      >
      <div class="col-md-6">
        <input
          type="text"
          id="name"
          name="name"
          class="form-control"
          required
        />
      </div>
    </div>

    <div class="form-group row mb-3">
      <label for="description" class="col-md-6 col-form-label"
        ><strong>Description:</strong></label
      >
      <div class="col-md-6">
        <textarea
          type="text"
          id="description"
          name="description"
          class="form-control"
          required
        >
{{product.description}}</textarea
        >
      </div>
    </div>

    <div class="form-group row mb-3">
      <label for="quantity" class="col-md-6 col-form-label"
        ><strong>Quantity:</strong></label
      >
      <div class="col-md-6">
        <input
          type="number"
          id="quantity"
          name="quantity"
          class="form-control"
          required
        />
      </div>
    </div>

    <div class="form-group row mb-3">
      <label for="category" class="col-md-6 col-form-label"
        ><strong>Category:</strong></label
      >
      <div class="col-md-6">
        <input
          type="text"
          id="category"
          name="category"
          class="form-control"
          required
        />
      </div>
    </div>

    <div class="form-group row mb-3">
      <label for="weight" class="col-md-6 col-form-label"
        ><strong>Weight:</strong></label
      >
      <div class="col-md-6">
        <input
          type="number"
          id="weight"
          name="weight"
          class="form-control"
          required
        />
      </div>
    </div>

    <div class="form-group row mb-3">
      <label for="expiry_date" class="col-md-6 col-form-label"
        ><strong>Expiry Date:</strong></label
      >
      <div class="col-md-6">
        <input
          type="date"
          id="expiry_date"
          name="expiry_date"
          class="form-control"
          required
        />
      </div>
    </div>

    <div class="form-group row mt-5">
      <div class="col-md-6 offset-md-5">
        <button type="submit" class="btn btn-primary">Add Product</button>
      </div>
    </div>
  </form>
</div>
<script src="{{ url_for('static', filename='script.js') }}"></script>
{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Login Page{% endblock %} {% block
content %}
<div class="container d-flex justify-content-center align-items-center vh-100">
  <div class="col-md-6">
    <form method="POST">
      <h3 align="center">Login</h3>
      <div class="form-group">
        <label for="email"><strong>Email Address</strong></label>
        <input
          type="email"
          class="form-control"
          id="email"
          name="email"
          placeholder="Enter email"
        /><br />
      </div>
      <div class="form-group">
        <label for="password"><strong>Password</strong></label>
        <input
          type="password"
          class="form-control"
          id="password"
          name="password"
          placeholder="Enter password"
        />
      </div>
      <br />
      <div class="text-center">
        <!-- Center-align the button -->
        <button type="submit" class="btn btn-primary">Login</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

website/templates/update_product.html
{% extends "base.html" %} {% block title %} Update Product {% endblock %} {%
block navbar %} {# Empty block to exclude the navigation bar in products.html #}
{% endblock %} {% block content %} {# Empty block to exclude the content #} {%
endblock %} {% block admin%}
<div class="container-md">
  <h2 class="mt-4 mb-4">Update Product</h2>
  <form
    id="updateForm"
    method="post"
    action="{{ url_for('views.edit_product', sku=product.sku) }}"
    class="mx-auto"
  >
    <div class="form-group row mb-3">
      <label for="name" class="col-md-6 col-form-label"
        ><strong>Product Name:</strong></label
      >
      <div class="col-md-6">
        <input
          type="text"
          id="name"
          name="name"
          value="{{ product.name }}"
          class="form-control"
          required
        />
      </div>
    </div>

    <div class="form-group row mb-3">
      <label for="description" class="col-md-6 col-form-label"
        ><strong>Description:</strong></label
      >
      <div class="col-md-6">
        <textarea id="description" name="description" class="form-control">
{{ product.description }}</textarea
        >
      </div>
    </div>

    <div class="form-group row mb-3">
      <label for="quantity" class="col-md-6 col-form-label"
        ><strong>Quantity:</strong></label
      >
      <div class="col-md-6">
        <input
          type="number"
          id="quantity"
          name="quantity"
          value="{{ product.quantity }}"
          class="form-control"
          required
        />
      </div>
    </div>

    <div class="form-group row mb-3">
      <label for="category" class="col-md-6 col-form-label"
        ><strong>Category:</strong></label
      >
      <div class="col-md-6">
        <input
          type="text"
          id="category"
          name="category"
          value="{{ product.category }}"
          class="form-control"
        />
      </div>
    </div>

    <div class="form-group row mb-3">
      <label for="weight" class="col-md-6 col-form-label"
        ><strong>Weight (in pound):</strong></label
      >
      <div class="col-md-6">
        <input
          type="number"
          id="weight"
          name="weight"
          value="{{ product.weight }}"
          class="form-control"
        />
      </div>
    </div>

    <div class="form-group row mb-6">
      <label for="expiry_date" class="col-md-6 col-form-label"
        ><strong>Expiry Date:</strong></label
      >
      <div class="col-md-6">
        <input
          type="date"
          id="expiry_date"
          name="expiry_date"
          value="{{ product.expiry_date }}"
          class="form-control"
        />
      </div>
    </div>

    <div class="form-group row mt-5">
      <div class="col-md-6 offset-md-5">
        <button type="submit" class="btn btn-primary">Update Product</button>
      </div>
    </div>
  </form>
</div>
<script
  type="text/javascript"
  src="{{ url_for('static', filename='js/admin.js') }}"
></script>
{% endblock %}